export const ErrorCodes = Object.freeze({
  // ── Payment Errors ──
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_INVALID_TRANSITION: 'PAYMENT_INVALID_TRANSITION',
  PAYMENT_CONCURRENT_UPDATE: 'PAYMENT_CONCURRENT_UPDATE',
  PAYMENT_MAX_RETRIES_EXCEEDED: 'PAYMENT_MAX_RETRIES_EXCEEDED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_CREATION_FAILED: 'PAYMENT_CREATION_FAILED',

  // ── Idempotency Errors ──
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // ── Gateway Errors ──
  GATEWAY_UNAVAILABLE: 'GATEWAY_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  GATEWAY_REJECTED: 'GATEWAY_REJECTED',

  // ── Circuit Breaker ──
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',

  // ── Webhook Errors ──
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_DUPLICATE: 'WEBHOOK_DUPLICATE',
  WEBHOOK_PROCESSING_FAILED: 'WEBHOOK_PROCESSING_FAILED',

  // ── Validation Errors ──
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // ── System Errors ──
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
});

// HTTP status code mapping for error codes
export const ErrorHttpStatus = Object.freeze({
  [ErrorCodes.PAYMENT_NOT_FOUND]: 404,
  [ErrorCodes.PAYMENT_ALREADY_PROCESSED]: 409,
  [ErrorCodes.PAYMENT_INVALID_TRANSITION]: 422,
  [ErrorCodes.PAYMENT_CONCURRENT_UPDATE]: 409,
  [ErrorCodes.PAYMENT_MAX_RETRIES_EXCEEDED]: 422,
  [ErrorCodes.PAYMENT_SIGNATURE_INVALID]: 400,
  [ErrorCodes.PAYMENT_CREATION_FAILED]: 500,
  [ErrorCodes.IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCodes.GATEWAY_UNAVAILABLE]: 503,
  [ErrorCodes.GATEWAY_TIMEOUT]: 504,
  [ErrorCodes.GATEWAY_REJECTED]: 402,
  [ErrorCodes.CIRCUIT_OPEN]: 503,
  [ErrorCodes.WEBHOOK_SIGNATURE_INVALID]: 401,
  [ErrorCodes.WEBHOOK_DUPLICATE]: 200, 
  [ErrorCodes.WEBHOOK_PROCESSING_FAILED]: 500,
  [ErrorCodes.VALIDATION_ERROR]: 400,
  [ErrorCodes.INTERNAL_ERROR]: 500,
  [ErrorCodes.DATABASE_ERROR]: 500,
  [ErrorCodes.RATE_LIMIT_EXCEEDED]: 429,
});
